const BabyPics = {
    a: require('./a.webp').default,
    b: require('./b.webp').default,
    c: require('./c.webp').default,
    d: require('./d.webp').default,
    e: require('./e.webp').default,
    f: require('./f.webp').default,
    g: require('./g.webp').default,
    h: require('./h.webp').default,
    i: require('./i.webp').default,
    j: require('./j.webp').default,
    k: require('./k.webp').default,
    l: require('./l.webp').default,
    m: require('./m.webp').default,
    n: require('./n.webp').default,
    o: require('./o.webp').default,
    p: require('./p.webp').default,
    q: require('./q.webp').default,
    r: require('./r.webp').default,
    s: require('./s.webp').default,
    t: require('./t.webp').default,
    u: require('./u.webp').default,
    u2: require('./u2.webp').default,
    v: require('./v.webp').default,
    w: require('./w.webp').default,
    x: require('./x.webp').default,
    y: require('./y.webp').default,
    z: require('./z.webp').default,
    z3: require('./z3.webp').default,
    z4: require('./z4.webp').default,
    z5: require('./z5.webp').default
}

export default BabyPics;